// Generated by https://quicktype.io

export interface Country {
  name: string;
  independent: boolean;
}

export interface User {
  name: string;
  email: string;
  subscription: boolean;
  country?: Country;
  city: string;
}
