// Generated by https://quicktype.io

export interface University {
  domains: string[];
  alpha_two_code: AlphaTwoCode;
  country: Country;
  web_pages: string[];
  name: string;
  'state-province': null | string;
}

export enum AlphaTwoCode {
  Es = 'ES',
  GB = 'GB',
  Pt = 'PT',
}

export enum Country {
  Portugal = 'Portugal',
  Spain = 'Spain',
  UnitedKingdom = 'United Kingdom',
}
